"""为表添加字段

Revision ID: 48fb6ad581f3
Revises: 4ca7349ed686
Create Date: 2025-04-28 10:32:13.154590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fb6ad581f3'
down_revision = '4ca7349ed686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debunk_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('author_verified', sa.Boolean(), nullable=True),
    sa.Column('author_verified_type', sa.Integer(), nullable=True),
    sa.Column('author_verified_reason', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('attitudes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reposts_count', sa.Integer(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('publish_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('origin_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_table('weibo_debunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('weibo_mid_id', sa.String(length=50), nullable=True),
    sa.Column('weibo_user_id', sa.String(length=50), nullable=True),
    sa.Column('weibo_user_name', sa.String(length=100), nullable=True),
    sa.Column('user_verified', sa.Boolean(), nullable=True),
    sa.Column('user_verified_type', sa.Integer(), nullable=True),
    sa.Column('user_verified_reason', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('attitudes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reposts_count', sa.Integer(), nullable=True),
    sa.Column('pics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weibo_mid_id')
    )
    op.create_table('xinlang_debunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('news_id', sa.String(length=100), nullable=True),
    sa.Column('data_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('comment_id', sa.String(length=100), nullable=True),
    sa.Column('publish_time', sa.String(length=50), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xinlang_debunk')
    op.drop_table('weibo_debunk')
    op.drop_table('debunk_content')
    # ### end Alembic commands ###
