"""为User表添加字段

Revision ID: 4ca7349ed686
Revises: ac067dfa37b5
Create Date: 2025-04-26 03:30:10.096590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca7349ed686'
down_revision = 'ac067dfa37b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False, comment='消息标题'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
